Fix behat tests
sonata-project/sandbox pull request #637
Opened 2020-07-21 11:16 UTC by wbloszyk

2020-07-27 14:01 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2020-09-07 12:45 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2020-09-07 13:20 UTC, jordisala1991 commented on composer.lock
> -            "funding": [
seems like you are using an old composer version

2020-09-07 13:47 UTC, wbloszyk commented on composer.lock
> -            "funding": [
Upgraded to: 
Composer version 1.10.10 2020-08-03 11:35:19

from 1.6 :smiley:

2020-09-08 08:54 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2020-09-14 17:50 UTC, phansys requested changes

2020-09-14 17:50 UTC, phansys commented on config/packages/framework.yaml
> +        hinclude_default_template: ":default:hinclude.html.twig"
```suggestion
        hinclude_default_template: ':default:hinclude.html.twig'
```

2020-09-14 17:50 UTC, phansys commented on config/packages/sonata_customer.yml
> +        template:     '@SonataCustomer/Profile/action.html.twig'
```suggestion
        template: '@SonataCustomer/Profile/action.html.twig'
```

2020-09-14 17:50 UTC, phansys commented on config/packages/sonata_twig.yaml
> +        - { type: 'sonata_user_error' }
Missing LF at EOF.

2020-09-14 18:08 UTC, phansys commented on composer.json
> +        "sonata-project/twig-extensions": "1.4.1",
Do we really need an exact version here? Can't we trust on semver?

2020-09-14 18:19 UTC, wbloszyk commented on composer.json
> +        "sonata-project/twig-extensions": "1.4.1",
This change is require. 1.4.0 will be not working.
https://github.com/sonata-project/twig-extensions/pull/103/files

Fixed to "^1.4.1"

2020-09-14 18:28 UTC, phansys approved these changes

2020-09-14 18:37 UTC, merged