DevKit updates for master branch
sonata-project/sandbox pull request #812
Opened 2020-10-10 12:09 UTC by SonataCI

2020-10-10 14:03 UTC, jordisala1991 approved these changes

2020-10-10 14:03 UTC, jordisala1991 requested changes
Wop this one fails

2020-10-19 06:59 UTC, OskarStark commented
I fixed the CS errors.

@wbloszyk can you please check the failing test? Thanks

2020-10-19 07:52 UTC, wbloszyk commented
> I fixed the CS errors.
> 
> @wbloszyk can you please check the failing test? Thanks

Changed made on master was to big to allow keep tests working. This is add to[ `sandbox:3.0` TODO list](https://github.com/sonata-project/sandbox/issues/634).
Tests on `sandbox:master` should not be on yet.

2020-10-21 15:10 UTC, merged